summary(AirQuality)
AirQuality$X16=NULL
AirQuality[seq(9358,9471,1),]=NULL
summary(air$T)
hist(airt$T)
air=subset(air,air$T!=-200)
library(mice)
install.packages("mice")
head(airt$Time)
airt$Time=period_to_seconds(hms(airt$Time))
air$Time=seconds(hms(air$Time))
airt$Date=yday(airt$Date)
length(which(airt==-200|airt==-200.0))
airt$CO[airt$CO==-200]=NA
summary(airt$CO)
airt$NO2[airt$NO2==-200]=NA
airt$NOx.GT.[airt$NOx.GT.==-200]=NA
airt$Pb[airt$Pb==-200|airt$Pb==-200.0]=NA
simple=airt[,-14]
library(mice)
simple=complete(mice(simple))
summary(simple)
summary(airt$Date)
summary(air$Date)
airt$Date=air$Date
airt$Date=as.Date(airt$Date,"%m/%d/%Y")
head(airt$Time)
64800/3600
airt$Time=airt$Time/3600
summary(airt)
model=lm(T~.,data=airt)
summary(model)
head(airt$Time)
str(airt$Time)
AirQuality$Date=yday(as.Date(AirQuality$Date,"%m/%d/%Y"))
AirQuality$Time=period_to_seconds(hms(AirQuality$Time))
lao=read.csv("AirQuality.csv")
AirQuality$Time=period_to_seconds(hms(lao$Time))
AirQuality$Time=AirQuality$Time/3600
model=lm(T~.,data=AirQuality)
summary(model)
